stages:
  - build
  - test
  - deploy
  -
maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B"

maven-test:
  image: maven:3-jdk-8
  stage: test
  script: "mvn test -B"

deploy_test:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=api-login-atualize-stage --api-key=$HEROKU_API_KEY
    - echo “Deployed to Staging Server https://api-login-atualize-stage.herokuapp.com/"
  only:
    - master

deploy_production:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=api-login-atualize --api-key=$HEROKU_API_KEY
    - echo “Deployed to Production Server https://api-login-atualize.herokuapp.com/"
  when: manual
  only:
    - master
after_script:
  - echo “End CI”